### ISSUE TITLE
Missing icons (incomplete)

### ISSUE THREAD

**Issue by awhitford** [pd4d10/flutter-vector-icons#1]
I can not seem to find `home-group` for `MaterialCommunityIcons`.
See:  https://materialdesignicons.com/icon/home-group

**Comment by awhitford** [comment]
I also am unable to find some [FontAwesome](https://fontawesome.com/) icons, like:
* https://fontawesome.com/icons/umbrella-beach
* https://fontawesome.com/icons/dumbbell

I now notice that your README mentions "FontAwesome (v4.7.0, 675 icons)" while their web site says "5,097 Awesome Icons" -- that is a lot of stuff missing.  Care to comment to set expectations?

**Comment by ghost** [comment]
> 
> 
> I also am unable to find some [FontAwesome](https://fontawesome.com/) icons, like:
> 
>     * https://fontawesome.com/icons/umbrella-beach
> 
>     * https://fontawesome.com/icons/dumbbell
> 
> 
> I now notice that your README mentions "FontAwesome (v4.7.0, 675 icons)" while their web site says "5,097 Awesome Icons" -- that is a lot of stuff missing. Care to comment to set expectations?

I believe you are confusing the FontAwesome versions.
FontAwesome **v4.7.0** only has 675 icons. (cp. [fontawesome.com/v4.7.0/icons/](https://fontawesome.com/v4.7.0/icons/))
**v5.9.0**, has a lot more icons but isn't provided by this package and both icons you linked are not part of the v4.7.0 icon set.

**Comment by pd4d10** [comment]
Hi @awhitford , Thanks for your report.

Font Awesome 5 free fonts have been added in the latest v0.2.0

```dart
// Exported:
FontAwesome5Brands
FontAwesome5Regular
FontAwesome5Solid
```

**Comment by pd4d10** [comment]
`MaterialCommunityIcons` also updated, try

```dart
MaterialCommunityIcons.home_group
```

**Comment by pd4d10** [comment]
I'm going to close this issue. Feel free to reopen it if there are any problems.
