### ISSUE TITLE
Add New Library: Cupertino Icons

### ISSUE THREAD

**Issue by hardiklakhalani** [pd4d10/flutter-vector-icons#14]
Package: [cupertino_icons](https://pub.dev/packages/cupertino_icons)
Icon Widget: `Icon(CupertinoIcons.home)`

**Comment by pd4d10** [comment]
Hi, this lib is aimed to be a port of [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons), and will keep consistent with it.

Perhaps you can first submit it to react-native-vector-icons, and then we'll sync it here. Thanks!
