### ISSUE TITLE
Preview Gallery Link is broken

### ISSUE THREAD

**Issue by colbycornish** [pd4d10/flutter-vector-icons#15]
As the title says, the current preview gallery link 404's :)
<img width="1254" alt="Screenshot 2022-10-25 at 9 48 13 PM" src="https://user-images.githubusercontent.com/798842/197937151-297fc6e3-54be-4a44-bf60-f86ee3f2bead.png">

**Comment by pd4d10** [comment]
Hi, thanks for the feedback!

New preview link here: https://flutter-vector-icons.vercel.app/
