### ISSUE TITLE
Web Icon gallery not work

### ISSUE THREAD

**Issue by naccio8** [pd4d10/flutter-vector-icons#9]
Hi, congratulations on the library!
The only current problem I encounter is that the web page with the icons catalog does not work and it is practically impossible to choose which one to use without this preview part!
Can you restore it?

**Comment by pd4d10** [comment]
Thanks for the feedback! It should been fixed now.

**Comment by moesaid** [comment]
as of `Sep - 13 - 22 ` gallery not working

**Comment by pd4d10** [comment]
Thanks for the feedback! I'll check it
